### ISSUE TITLE
pandas on spark looking for wrong resource notebook

### ISSUE THREAD

**Issue by robkisk** [databricks-demos/dbdemos#1]
After running `dbdemos.install('pandas-on-spark', path='./', overwrite = True)` it looks like the initialization is pointing to a missing notebook:

![image](https://user-images.githubusercontent.com/113189551/201931961-578ebe80-755b-4aa0-a2a0-e50d4436d5a6.png)

**Comment by QuentinAmbard** [comment]
looks like the notebook was missing from the bundle - wasn't catch by the tests because data already exists in when the test run, I'll have to fix that.
Can you try again? I just updated the wheel to add it (make sure you run pip install with --force to reinstall the wheel)

**Comment by robkisk** [comment]
looks good. thanks!
