### ISSUE TITLE
Install codes only without running

### ISSUE THREAD

**Issue by SomanathSankaran** [databricks-demos/dbdemos#103]
Hi Team,

I just need to clone all the demos inside my workspace without running cluster.
Is there any option to do this

**Comment by QuentinAmbard** [comment]
Sure, just add `start_cluster = False` and it should do what you want

**Comment by SomanathSankaran** [comment]
No despite that it is working @QuentinAmbard

**Comment by QuentinAmbard** [comment]
ah I see it'll be starting the job at the end (you can also use use_current_cluster to avoid cluster creation)
I can add an option to only load the notebooks let me reopen this
