### ISSUE TITLE
Couldn't create or update a dashboard

### ISSUE THREAD

**Issue by AnnaWykes** [databricks-demos/dbdemos#104]
Hi I get an error when trying to install, it runs fine if I disable the dashboard creation:

![image](https://github.com/databricks-demos/dbdemos/assets/9929373/a792237a-d453-4b71-8de7-840991c7f941)

![image](https://github.com/databricks-demos/dbdemos/assets/9929373/68da5090-c740-4a0a-b935-f143dac9138e)

![image](https://github.com/databricks-demos/dbdemos/assets/9929373/e91d1a96-03cd-4f46-95b7-e042217b3a43)

![image](https://github.com/databricks-demos/dbdemos/assets/9929373/7baa6e84-0dc4-4b36-975b-a1743c229e1a)

![image](https://github.com/databricks-demos/dbdemos/assets/9929373/ae259d62-2da8-4434-b92b-1c0e68c8383d)

Can you advise how to troubleshoot this?

**Comment by QuentinAmbard** [comment]
Hi @AnnaWykes , I'm having a look, I'll let you know we're trying to reproduce on our side.

**Comment by QuentinAmbard** [comment]
hey, this should be fixed with the latest release, give it a try & let us know if it's not the case!
