### ISSUE TITLE
list_demos() UI boxes not big enough for llm-fine-tuning text, causes issues with selecting

### ISSUE THREAD

**Issue by datasmithing-holly** [databricks-demos/dbdemos#128]
The text description for the fine tuning is too long to fit in the available space. This is not just a UI issue - when selecting `dbdemos.install('llm-fine-tuning')` it overlaps with MLflow, so you end up copying that into your cell. 

<img width="392" alt="Screenshot 2024-07-01 at 10 48 28" src="https://github.com/databricks-demos/dbdemos/assets/50494163/573b5e6a-6f33-4312-8a11-5be6256696a6">

**Comment by QuentinAmbard** [comment]
thanks, we're updating the fine tuning with a simpler version soon I'll fix that too!

**Comment by QuentinAmbard** [comment]
should be fixed!
