### ISSUE TITLE
DLT Dataset (Lending Tree)?

### ISSUE THREAD

**Issue by Fallinggator** [databricks-demos/dbdemos#13]
I tried to use the full DLT demo, but ran into a few problems.

1. Had to manually alter the cluster it tried to create to use a cluster policy since required by my org. (Resolved, but would be nice if aspects like that were easily configurable with args)

2. Failed to load the lending tree dataset csv. I couldn't find it anywhere in the workspace samples or in the repo. I looked on Kaggle, but there are too many potential matches. No idea which of the lending tree data sets it is expecting.

**Comment by karthik25-gk** [comment]
Having the same issue with the dataset csv. Can I know where I can download from.

**Comment by QuentinAmbard** [comment]
ok I'll have a look, must be a bundle issue

**Comment by QuentinAmbard** [comment]
@Fallinggator  I'm not sure I'm looking at the right place, are you saying you don't have this dataset in your workspace ?

spark.read.csv('/databricks-datasets/lending-club-loan-stats', header=True)  ?

Can you confirm which demo you're loading and where it's failing exactly ?
Thanks

**Comment by karthik25-gk** [comment]
@QuentinAmbard Ignore my issue. It’s been resolved. Thanks

**Comment by QuentinAmbard** [comment]
Ok I understand what happened, becuase you can't create the cluster, the init job did not start, and the data wasn't generated. I'll instead start the init job with the current cluster, it'll be faster & solve these kind of issue.
