### ISSUE TITLE
uc-04-system-tables : No dashboards generated

### ISSUE THREAD

**Issue by TheRealJimShady** [databricks-demos/dbdemos#130]
**Cloud : Azure**
**Demo Name : uc-04-system-tables**

The notebook `00-intro-system-tables` contains a link in the sentence '_Open the dashboard to review the informations available for you_.'  which, when clicked, opens a tab with the title 'My Legacy Dashboards'. The dashboard doesn't open and after searching the workspace, it doesn't seem to exist 😕 is there something I should have done first? (I have already run the job named `dbdemos_billing_forecast_init_[username]`) 

![image](https://github.com/user-attachments/assets/7c719e53-f76d-41d8-9b62-1864b7d950a0)

**Comment by QuentinAmbard** [comment]
should be fixed !
