### ISSUE TITLE
Lakehouse C360 not using the `use_current_cluster=True` parameter

### ISSUE THREAD

**Issue by mechevarria** [databricks-demos/dbdemos#132]
I'm getting an error on the Lakehouse C360 demo when trying to run it with classic compute in an AWS environment. I am getting a INVALID_PARAMETER_VALUE for using an existing cluster, even though I am passing in the use_current_cluster=True option. This error did not come up trying to run the lakehouse-iot-platform demo, so seems isolated

![error1](https://github.com/user-attachments/assets/44195927-5469-4d4f-90e0-8ec7320542ab)
![error2](https://github.com/user-attachments/assets/43dde595-961d-4c4f-adfb-193a5b50aab8)
![error3](https://github.com/user-attachments/assets/ca6a67a4-fe48-49e8-a76e-cab47985d415)

**Comment by QuentinAmbard** [comment]
hey, this should have been fixed a few days ago, let me know if it's still happening!
