### ISSUE TITLE
path correction in dbdemo-fsi-credit

### ISSUE THREAD

**Issue by mechevarria** [databricks-demos/dbdemos#133]
When running the pipeline, the cloud_files path is incorrect. The `credit-decisioning` folder needs to be removed from the path

![Screenshot 2024-08-20 112425](https://github.com/user-attachments/assets/0f47c727-69de-4f53-83ac-128cb543e9c6)
![Screenshot 2024-08-20 112444](https://github.com/user-attachments/assets/29db56b9-0426-42ec-809b-c118784600b5)

**Comment by QuentinAmbard** [comment]
thanks, it was fixed in the repo but not packaged :/ I'll re-release it sorry about that!
