### ISSUE TITLE
fsi_fraud_detection DLT pipeline is failing

### ISSUE THREAD

**Issue by kuldeep-in** [databricks-demos/dbdemos#134]
fsi_fraud_detection DLT pipeline is failing, looks like some of the data sources are missing in the init script.

`rg.apache.spark.sql.catalyst.ExtendedAnalysisException: Unable to process statement for Table 'fraud_reports'`

`com.databricks.sql.cloudfiles.errors.CloudFilesException: Cannot infer schema when the input path `/Volumes/uc_kuldeep01/fsi_fraud_detection/fraud_raw_data/fraud_report` is empty. Please try to start the stream when there are files in the input path, or specify the schema`

**Comment by QuentinAmbard** [comment]
hey, I believe this is fixed, if you run 00-setup it'll generate all the data properly. I'm going to close it for now, please re-open if you still face this issue
