### ISSUE TITLE
uc-04-system-tables - Data Initialization job fails due to missing dep "prophet"

### ISSUE THREAD

**Issue by jasonscalia** [databricks-demos/dbdemos#135]
Hello,

The `uc-04-system-tables` data initialization job currently fails due to the `prophet` dep not being installed. Running `%pip install prophet` and re-running the job causes it to complete without error.

Version: dbdemos-0.5.13

**Comment by QuentinAmbard** [comment]
thanks, I added it, it was designed to run with MLRuntime, we'll fix them all with the serverless update soon.
