### ISSUE TITLE
02-DLT-Loan-pipeline broken link for DQ dashboard

### ISSUE THREAD

**Issue by chhayavishwakarma** [databricks-demos/dbdemos#14]
DQ dashboard link refers to internal databricks - which ofcourse is not openable - https://e2-demo-field-eng.cloud.databricks.com/sql/dashboards/9c87ac15-b19b-4d05-a305-11affd1d8f12-dlt---retail-data-quality-stats?o=1444828305810485
<img width="464" alt="DQ" src="https://user-images.githubusercontent.com/7696087/222761297-88d765a6-73bb-4d9a-b3c6-c44117c31a1b.png">

**Comment by QuentinAmbard** [comment]
Thanks @chhayavishwakarma, I just fixed it, it will be in the next release - sorry for the delay !

**Comment by chhayavishwakarma** [comment]
thank you
