### ISSUE TITLE
llm-tools-functions demo has an agent function that does not work with Playground

### ISSUE THREAD

**Issue by hiydavid** [databricks-demos/dbdemos#142]
The `recommend_outfit_description` function which calls on the Llama 3.1 70b via `ai_query` to make clothing recommendation based on temperature, rain, and a style description. This function works in a notebook. 

However, if you try to use it in Playground via `Tools` then it produces this error:

<img width="795" alt="Screenshot 2024-10-08 at 8 57 36 AM" src="https://github.com/user-attachments/assets/ca446469-6f8d-4ac0-bbec-c058c9d7ff1f">

**Comment by QuentinAmbard** [comment]
@hiydavid I believe we fixed it, the main remaining issue is that your serverless compute will do an external egress request, so you need to go to the network option as an admin and allow the egress call.
I added a comment to clarify it in the notebook it'll be in the next release - I'll close the ticket, let me know if it still doesn't work after that.
