### ISSUE TITLE
lakehouse-fsi-smart-claims fails if a schema different than 'fsi_smart_claims' is used when installing

### ISSUE THREAD

**Issue by maucaro** [databricks-demos/dbdemos#143]
I installed the lakehouse-fsi-smart-claims demo with the following command:
`dbdemos.install('lakehouse-fsi-smart-claims', catalog='maucaro_demos', schema='pitch_demo')`

The pipeline threw a few errors, one of which was:
[SCHEMA_NOT_FOUND] The schema `maucaro_demos.fsi_smart_claims` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a catalog, verify the current_schema() output, or qualify the name with the correct catalog.
To tolerate the error on drop use DROP SCHEMA IF EXISTS. SQLSTATE: 42704

I reinstalled the demo, this time specifying 'fsi_smart_claims' as the schema, and the installation was successful.

**Comment by QuentinAmbard** [comment]
thanks good catch, we changed the default to dbdemos_fsi_smart_claims and kept the old one in the DLT pipeline, it'll be in the next release!
