### ISSUE TITLE
DLT-Expectations notebook does not exist in C360: Reducing Customer Churn

### ISSUE THREAD

**Issue by rcmarxDBX** [databricks-demos/dbdemos#144]
There should be notebook **DLT-expectations-dashboard-data-prep** in the downloaded notebook, that seems to be absent.

This notebook is used to support the Data Quality dashboard that accompanies the demo.

**Comment by QuentinAmbard** [comment]
<img width="382" alt="image" src="https://github.com/user-attachments/assets/99dcdd04-726b-482c-9c50-43241b81ad5f">
I do see it, are you sure it's not here?

**Comment by QuentinAmbard** [comment]
alright I found the issue - will be in the next release thanks!
