### ISSUE TITLE
streaming-sessionization fails

### ISSUE THREAD

**Issue by ilias-giannakos** [databricks-demos/dbdemos#146]
Hello on the demo streaming-sessionalization -> notebook _00-Delta-session-PRODUCER it fails to run on command #5 
```
kafka_bootstrap_servers_tls = "b-1.oetrta.kpgu3r.c1.kafka.us-west-2.amazonaws.com:9094,b-3.oetrta.kpgu3r.c1.kafka.us-west-2.amazonaws.com:9094,b-2.oetrta.kpgu3r.c1.kafka.us-west-2.amazonaws.com:9094"

from kafka import KafkaProducer
producer = KafkaProducer(security_protocol="SSL", bootstrap_servers=kafka_bootstrap_servers_tls.split(","), value_serializer=lambda x: x.encode('utf-8'))
```
the error is NoBrokersAvailable: NoBrokersAvailable

Can you please look into it?

**Comment by QuentinAmbard** [comment]
hi @ilias-giannakos , for now we sadly don't expose these kafka brokers publically (our team is only using them internally), and you'll have to configure your own to have the demo working properly. I just added a comment to clarify that in the demo, it should land in the next release.
