### ISSUE TITLE
MLOps-End2End: Error about there is not parent directory and wrong code for create Online Table

### ISSUE THREAD

**Issue by chik-taks** [databricks-demos/dbdemos#155]
When I run a Jobs in dbdemos "MLOps-End2End", there are 2 errors.

1. There is not parent directory.

Detail:
In the _resources/00-setup, you define the path of experiments.
```
if is_advanced_mlops_demo:
  # Set Experiment name as default
  xp_path = f"/Users/{current_user}/databricks_automl"
  xp_name = "advanced_mlops_churn_demo_experiment"
```

So in the task "adv_training" cell 6, this code makes error 
```
mlflow.set_experiment(f"{xp_path}/{xp_name}")
-> RestException: RESOURCE_DOES_NOT_EXIST: Parent directory /Users/<<<username>>>/databricks_automl does not exist.
```

Solution:
before run, check directory and mkdir if not exist.

2. Wrong code for creating Online Table.

there is this code in the notebook and makes error about wrong create func.
```
online_table = w.online_tables.create(
  name=f"{catalog}.{db}.advanced_churn_feature_table_online_table",
  spec=churn_features_online_store_spec
)
```

maybe correct code is following:

```
from databricks.sdk.service.catalog import OnlineTable

online_table = OnlineTable(
  name=f"{catalog}.{db}.advanced_churn_feature_table_online_table",
  spec=churn_features_online_store_spec
)

w.online_tables.create_and_wait(table=online_table)
```

**Comment by QuentinAmbard** [comment]
Thanks @chik-taks! 
@cylee-db is https://github.com/databricks-demos/dbdemos-notebooks/pull/93/ fixing the second point?

for `xp_path = f"/Users/{current_user}/databricks_automl"` I imagine we're not using the current folder cause it won't work on a repo, maybe instead switch to the /Shared/dbdemos folder that's what we usually do

**Comment by QuentinAmbard** [comment]
awesome, thanks everybody !! Closing this & merging the PR 93!
