### ISSUE TITLE
RAG-LLM-RAG > first step > create vector search index

### ISSUE THREAD

**Issue by BricksterMikeWang** [databricks-demos/dbdemos#156]
got the following error:
Exception: Response content b'{"error_code":"QUOTA_EXCEEDED","message":"Maximum number of indexes per endpoint exceeded for vector search endpoint dbdemos_vs_endpoint. Current number of indexes 50 must be less than 50."}', status_code 400
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c005a7c4-6232-4b61-b2b9-ae89ca0e8911/lib/python3.12/site-packages/databricks/vector_search/utils.py:78, in RequestUtils.issue_request(url, method, token, params, json, verify, auth, data, headers)
     77 try:
---> 78     response.raise_for_status()
     79 except Exception as e:
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c005a7c4-6232-4b61-b2b9-ae89ca0e8911/lib/python3.12/site-packages/databricks/vector_search/utils.py:81, in RequestUtils.issue_request(url, method, token, params, json, verify, auth, data, headers)
     79 except Exception as e:
     80     logging.warn(f"Error processing request {e}")
---> 81     raise Exception(
     82         f"Response content {response.content}, status_code {response.status_code}"
     83     )
     84 return response.json()

**Comment by QuentinAmbard** [comment]
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/c98cdf0d-ef53-4dcd-94f2-667593fd00d8">
I added an error message on top of the exception you have
