### ISSUE TITLE
image missing in aibi

### ISSUE THREAD

**Issue by QuentinAmbard** [databricks-demos/dbdemos#158]
@calreynolds these are the missing images:

https://github.com/databricks-demos/dbdemos-resources/blob/main/icon/aibi-portfolio-assistant-dashboard-0.png?raw=true
https://github.com/databricks-demos/dbdemos-resources/blob/main/icon/aibi-patient-genomics-dashboard-0.png?raw=true
https://github.com/databricks-demos/dbdemos-resources/blob/main/icon/aibi-supply-chain-forecasting-dashboard-0.png?raw=true
https://github.com/databricks-demos/dbdemos-resources/blob/main/icon/aibi-sales-pipeline-review-dashboard-0.png?raw=true
https://github.com/databricks-demos/dbdemos-resources/blob/main/icon/aibi-marketing-campaign-dashboard-0.png?raw=true

**Comment by calreynolds** [comment]
Affirmative -- adding now 🫡 .

**Comment by calreynolds** [comment]
https://github.com/databricks-demos/dbdemos-resources/pull/25

**Comment by calreynolds** [comment]
PR merged! Closing this issue
