### ISSUE TITLE
Wrong hyperlink text

### ISSUE THREAD

**Issue by souvik-databricks** [databricks-demos/dbdemos#18]
Hi @QuentinAmbard 

Great work on this **_dbdemos.ai_** beauty.

I was using dbdemos.install("dlt-loans")
And as you can see in the below picture for the python version of the notebook the hyperlink is named as SQL like below

**02-DLT-Loan-pipeline-PYTHON: [DLT pipeline definition (SQL)]()**
![image](https://user-images.githubusercontent.com/98817232/224388034-20153634-240e-45f0-9ab7-0daacf73028a.png)

The typo in the Text needs to be fixed it should be 
> **02-DLT-Loan-pipeline-PYTHON: [DLT pipeline definition (PYTHON)]()**

**Comment by QuentinAmbard** [comment]
Thanks, just fixed it, it'll be in the next release!
