### ISSUE TITLE
magic command UDF and DLT issue 

### ISSUE THREAD

**Issue by tjjazzy14** [databricks-demos/dbdemos#19]
in the lakehouse-iot-platform wind turbine demo
A DLT pipeline was created and points to two notebooks both having magic commands.
the magic command tied to a UDFs to install ML model. 
Are there detailed steps to install the model outside the DLT pipeline and set the needed parameters?
Also there are %pip libraries to install in the '01.2' notebook - looking for guidance

**See Notebooks**, '01.1-DLT-Wind-Turbine-SQL' and '01.2-DLT-Wind-Turbine-SQL-UDF' 

**Expected behavior** : As expected, the DLT pipeline fails on the magic commands and when commented out the code is using a UDF that was not registered due to the magic command.

Current Workaround in progress: Using SQL UDF. No workaround for libraries needed for ML model

Thanks in advance.

**Comment by QuentinAmbard** [comment]
Hi, I'm not sure I understand your question. The python loading the UDF is ignored in the SQL notebook but it should be just a warning (not a failure), that's why we have the 01.2-DLT-Wind-Turbine-SQL-UDF notebook being in python to load the UDF.
Can you send a screenshot of your error ?

The libraries used for the model are installed at the begining so it should also work fine with the %pip install.
In a real deployment you'd likely not hardcode the version like we did in the demo (instead load them from the requirement.txt file saved with the model in the registry)

**Comment by tjjazzy14** [comment]
Thanks for the quick response.
When I dig into the error this is what I am getting on a recent DLT run:
java.lang.RuntimeException: Failed to execute python command for notebook '/Users/username/dbdemos/lakehouse-iot-platform/01-Data-ingestion/01.2-DLT-Wind-Turbine-SQL-UDF' with id RunnableCommandId
RestException: RESOURCE_DOES_NOT_EXIST: RegisteredModel 'dbdemos_turbine_maintenance' does not exist. It might have been deleted.,Map(),Map(),List(),List(),Map())

<img width="438" alt="image" src="https://user-images.githubusercontent.com/7720930/226687317-7e353ad6-6bad-4ca5-9a6b-002f8f97408f.png">

<img width="421" alt="image" src="https://user-images.githubusercontent.com/7720930/226687240-847cc2fa-856a-4fd9-b2bc-9ceb2259df0a.png">

**Comment by tjjazzy14** [comment]
Hi,
I have resolved my issue with the demo setup.
Ran into a subscription quota error while running the below code.
`import dbdemos`
`dbdemos.install('lakehouse-iot-platform', overwrite=True)`

The code above needs compute resources, and it runs a job which also needs compute resources to install the data (see below screenshot).
<img width="515" alt="image" src="https://user-images.githubusercontent.com/7720930/226728001-cf77f83e-be26-4e7b-b0de-3734a85b97e3.png">

Error:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/7720930/226729332-5490c5dc-f6be-48fc-a9f1-b68cc4cf92aa.png">

My Learnings: If running this on community edition or using a subscriptions with cost quotas,  be mindful of how many compute resources are running at once per your quotas. For Azure you can request to increase the subscription quota if needed.
