### ISSUE TITLE
typo in uc-1-acl

### ISSUE THREAD

**Issue by sastafford** [databricks-demos/dbdemos#22]
Notebook: 00-UC-Table-ACL
Cmd 15: 

Current
`COPY INTO uc_acl.customers  FROM '/demos/uc/users' FILEFORMAT=JSON `

Fix
`COPY INTO uc_acl.customers  FROM '/dbdemos/uc/users' FILEFORMAT=JSON `

**Comment by QuentinAmbard** [comment]
thanks @sastafford - sorry I missed this one, just fixed it! Will be in the next released
