### ISSUE TITLE
Notebooks links are not working in chatbot demo

### ISSUE THREAD

**Issue by murtasy** [databricks-demos/dbdemos#25]
https://www.dbdemos.ai/demo-notebooks.html?demoName=llm-dolly-chatbot
Notebook links are giving 404 error in above tutorial.

**Comment by adityakadrekar16** [comment]
I am still getting the 404 error. Can you please check?

<img width="788" alt="image" src="https://user-images.githubusercontent.com/43070287/235550881-56766383-eedd-43f0-9b9f-e15870afcb7c.png">

**Comment by QuentinAmbard** [comment]
It's working well for me, the only thing is that I have to wait ~5sec to load all the notebook entirely as we change the links in javascript. Is that not working for you ?
