### ISSUE TITLE
Use of Unity Catalog in 'delta-lake' demo

### ISSUE THREAD

**Issue by brain246** [databricks-demos/dbdemos#27]
Hello there!

I just installed the 'delta-lake' demo in our (unity catalog enabled) workspace.

When running `%run ./_resources/00-setup $reset_all_data=$reset_all_data` everything worked, but not as expected, as i got a "Unity Catalog seems not to be enabled[...]" type message and well, unity catalog was not used.

I looked into the code and then found out that the access mode of the created cluster (custom) prevents Unity Catalog from being used. Maybe that is mentioned somewehere and I didn't read properly, but just in case a little heads-up. After setting the created cluster to single-user, everything worked fine and a catalog was created.

Cheers,
Thomas

PS: Everything else worked like a charm with your demos so far!

**Comment by QuentinAmbard** [comment]
hi @brain246 ! Thanks for your comment
Indeed it's not really being used but we have it in the shared init script setup
I'm adding it in the cluster conf - will be fixed with the next release.

Glad to hear that the rest worked well for you :)
