### ISSUE TITLE
load_in_8bit Dolly demo for smaller GPUs code incorrect

### ISSUE THREAD

**Issue by tj-cycyota** [databricks-demos/dbdemos#30]
In the Dolly demo, notebook `03-Q&A-prompt-engineering-for-dolly`, there is sample code provided (originally commented out) that looks like:

`# Note: if you use dolly 12B or smaller model but a GPU with less than 24GB RAM, use 8bit. This requires %pip install bitsandbytes`
`# instruct_pipeline = pipeline(model=model_name, load_in_8bit=True, trust_remote_code=True, device_map="auto")`

However, the correct way to pass the `load_in_8bit` param according to the [Databricks Dolly Docs](https://github.com/databrickslabs/dolly/blob/fc22734003b5ef5731ccbb8ecb469d7aa2afe175/README.md?plain=1#LL80C8-L80C43) is as:
`instruct_pipeline = pipeline(model=model_name, torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="auto", return_full_text=True, max_new_tokens=256, top_p=0.95, top_k=50, model_kwargs={'load_in_8bit': True})`

**Comment by tj-cycyota** [comment]
Not in my testing. The only way it works (e.g. actually load the model on a smaller GPU) is with setting `model_kwargs={'load_in_8bit': True}`

**Comment by QuentinAmbard** [comment]
so change to this right?

```  
# Note: if you use dolly 12B or smaller model but a GPU with less than 24GB RAM, use 8bit. This requires %pip install bitsandbytes
  # instruct_pipeline = pipeline(model=model_name, load_in_8bit=True, trust_remote_code=True, device_map="auto", model_kwargs={'load_in_8bit': True})
```

**Comment by tj-cycyota** [comment]
You have `load_in_8bit=True` in there twice. It should be this, with that param in `model_kwargs`:

```
# Note: if you use dolly 12B or smaller model but a GPU with less than 24GB RAM, use 8bit. This requires %pip install bitsandbytes
# instruct_pipeline = pipeline(model=model_name, trust_remote_code=True, device_map="auto", model_kwargs={'load_in_8bit': True})
```

**Comment by QuentinAmbard** [comment]
Thanks, I'm adding it in the next release
