### ISSUE TITLE
dbdemos-uc-05-upgrade: Unable to access s3a bucket

### ISSUE THREAD

**Issue by claraazevedo99** [databricks-demos/dbdemos#36]
Is it normal that I can't access it? I have trouble accessing all the aws buckets in several demos
![image](https://github.com/databricks-demos/dbdemos/assets/126807464/3974a783-409a-4c9b-93c3-a391b280678c)

I receive the following error:
![image](https://github.com/databricks-demos/dbdemos/assets/126807464/8741e01b-e5f7-4573-ba51-98da1e7910fb)

**Comment by QuentinAmbard** [comment]
yes, sadly we don't have an open bucket for our customers to test directly, you need to change by your own (the one you have is what we're using internaly at Databricks for our demos/tests).
You need to setup your own bucket + external location
I'll add a note so that it's more clear.

**Comment by claraazevedo99** [comment]
thank you for the reply!

**Comment by QuentinAmbard** [comment]
I added the note in the new release, hopefully it'll clarify things. Let me know if that's not the case happy to review that
