### ISSUE TITLE
dlt-loans issues

### ISSUE THREAD

**Issue by tiantan32** [databricks-demos/dbdemos#39]
In the last session “Tracking data quality” in 02-DLT-Loan-pipeline-PYTHON notebook, the reference link seems wrong:
- The how to access your DLT metrics link should be referring to "$./03-Log-Analysis" instead of "$./02-Log-Analysis".
- The data quality dashboard example link sent to a dashboard that’s been trashed

**Comment by QuentinAmbard** [comment]
thanks, I fixed it it should be in the next release. For the dashboard you can re-install it it should be restored
