### ISSUE TITLE
Incorrect URL redirection - Page Not Found (error 404)

### ISSUE THREAD

**Issue by SethiAbhinav** [databricks-demos/dbdemos#40]
Hi @QuentinAmbard 

I was going through the [Build your Chat Bot with Dolly](https://www.dbdemos.ai/demo-notebooks.html?demoName=llm-dolly-chatbot) demo and I encountered an issue when trying to access the notebooks hyperlinked in the tutorial (image below is one of the three notebooks mentioned in the tutorial).

<img width="813" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/84278440/2ba5fae9-7571-4df7-a7a8-ed0e0add760e">

The links redirect us to:
https://www.dbdemos.ai/minisite/llm-dolly-chatbot/$./02-Data-preparation
https://www.dbdemos.ai/minisite/llm-dolly-chatbot/$./03-Q&A-prompt-engineering-for-dolly
https://www.dbdemos.ai/minisite/llm-dolly-chatbot/$./04-chat-bot-prompt-engineering-dolly

The `$./` should be removed as the correct URLs are:
https://www.dbdemos.ai/minisite/llm-dolly-chatbot/02-Data-preparation
https://www.dbdemos.ai/minisite/llm-dolly-chatbot/03-Q&A-prompt-engineering-for-dolly
https://www.dbdemos.ai/minisite/llm-dolly-chatbot/04-chat-bot-prompt-engineering-dolly

**Comment by QuentinAmbard** [comment]
Hi @SethiAbhinav , it's working well for me, what's happening is that we have a javascript script changing the links to remove the $
(The $ are required when we install the notebooks in the workspace to have the relative links)

Which browser are you using? Do you see an error in the javascript console maybe?

<img width="664" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/96781/6748ec18-46b6-4423-9c97-5323aff8b376">

**Comment by SethiAbhinav** [comment]
Oh I see. That's insightful.

I am using these:
Brave browser
MAC OS

**Comment by QuentinAmbard** [comment]
I see I definitely did not test with Brave
Would you mind trying with another browser just to confirm that's the issue?

**Comment by SethiAbhinav** [comment]
I tested with three browsers now. Issue seems to persist. Attaching screen snaps for the same:

1) Brave: 
<img width="1408" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/84278440/7f6bd13a-5f2c-4149-b1d9-d2293723ada7">

2) Chrome:
<img width="1217" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/84278440/9e7b3bdf-6afd-4234-a181-39fb50cd1080">

3) Safari:
<img width="1104" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/84278440/f9b4f38b-cd3c-4f0d-af51-911f4a433c24">

**Comment by SethiAbhinav** [comment]
It seems to me that the href isn't updating correctly.

<img width="1096" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/84278440/9ef8843c-b7ba-454d-a859-e79cfb167ba9">


In the console there isn't any error related to this. I had some shields set up which auto disable some code from running on websites. But, even after removing it, the same sites load up.

**Comment by SethiAbhinav** [comment]
Tried it on a friend's device. It seems to be working fine on their device. I will try debugging what's going on in my systems. You can close this issue if you'd like.
