### ISSUE TITLE
uc-04-system-tables: Dashboards not getting created

### ISSUE THREAD

**Issue by ankurmitujjain** [databricks-demos/dbdemos#48]
I have premium databricks workspace and is able to install uc-04-system-tables demo without dashboard by below command.
dbdemos.install('uc-04-system-tables',  use_current_cluster = True, overwrite= True, skip_dashboards  = True)

I have to install it outside of main catalog (Not accessible), so had skipped dashboard creation, how can I create dashboard after installation? Is it possible to have queries + dashboard available as resources? which I can import?

Demo installation stops when I run below command...
dbdemos.install('uc-04-system-tables',  use_current_cluster = True, overwrite= False, skip_dashboards  = False)
![image](https://github.com/databricks-demos/dbdemos/assets/1140475/46cd6866-881f-4af7-ad2b-07dd6ca0d7aa)

**Comment by ankurmitujjain** [comment]
@QuentinAmbard is it possible to provide a zip of dashboard/sql queries?

**Comment by QuentinAmbard** [comment]
[dashboard.zip](https://github.com/databricks-demos/dbdemos/files/12094491/dashboard.zip)

here there are, if you have the preview enabled for import/export you can use it to load the dashboard by importing ab3b5298-e09e-4998-8ef3-ae456a7b888d_import_api.json
the other one is what we use with dbsqlclone waiting for the import/export to go public preview.

You can open the job to see the error in more details?

**Comment by ankurmitujjain** [comment]
> w

Job doesnt fails, but continue to run for infinite period... job query expects table to be available in main catalog, which in my case I had changed to a different catalog...

**Comment by QuentinAmbard** [comment]
Hey, we did a new release, could you try again see if it works better now?
If not can you share where the job is stuck? You can send it by email if you don't want to share it directly here: quentin.ambard@databricks.com

**Comment by ankurmitujjain** [comment]
Thanks @QuentinAmbard I tested it.. and it really worked like a charm... I was able to create and share cost mgmt dashboard with our other colleagues...
