### ISSUE TITLE
uc-04-system-tables: can't view _enable_system_tables notebook, 404

### ISSUE THREAD

**Issue by gfree76** [databricks-demos/dbdemos#49]
on the page https://www.dbdemos.ai/demo-notebooks.html?demoName=uc-04-system-tables, when I click the link for the _enable_system_tables notebook, it takes me to https://www.dbdemos.ai/minisite/uc-04-system-tables/$./_enable_system_tables and gives a 404

**Comment by QuentinAmbard** [comment]
Thanks, I just fixed it in databricks.com: 
https://notebooks.databricks.com/demos/uc-04-system-tables/index.html#

I'll redirect to this page very soon
