### ISSUE TITLE
Missing image for Spark Streaming Advanced tile

### ISSUE THREAD

**Issue by vinoaj** [databricks-demos/dbdemos#5]
https://github.com/databricks-demos/dbdemos/blob/a489a7cfeaaf60d565149b7642c91b1f53228669/dbdemos/dbdemos.py#L147

<img width="446" alt="image" src="https://user-images.githubusercontent.com/1736030/208272292-ad2287c3-f67a-4a70-985c-566caa6d5939.png">

Refers to `https://github.com/QuentinAmbard/databricks-demo/raw/main/resources/spark-streaming-sessionization.png` but that path returns a 404

**Comment by QuentinAmbard** [comment]
Thanks it was a duplicated, the new package version should fix that!
