### ISSUE TITLE
uc-04-system-tables: resources don't get placed if install fails

### ISSUE THREAD

**Issue by gfree76** [databricks-demos/dbdemos#50]
I'm trying to deploy to a workspace where we have a shared UC, and no one is supposed to write to the main catalog. When I run the install command, I get an error that says that I don't have permissions to the main catalog. I would like to modify the scripts to deploy to my own catalog, but that doesn't cause the install to succeed. Instead, new sql scripts are placed and run. 

I would also be okay with just running the notebooks, but that's not possible because they reference a resources folder that isn't being placed. If the resources were placed before trying to run the install, I would be able to hack this up myself. 

Is it possible for me to just copy the resources from somewhere?

**Comment by QuentinAmbard** [comment]
Hi @gfree76 , could you share your install error? 
I suspect that's the dashboard install, in this case you can do skip_dashboard = True and it'll install the package.
We're adding an option to specify your schema/database in the install but it'll take us a few extra weeks!

**Comment by gfree76** [comment]
Hey Quentin, thanks for the reply, and sorry for the delay.

> Installation error: Dashboard import fail - could not run the widget queries: SQL query error.
> The dashboard has widget queries, and these queries need to be run before importing other queries.
> dbdemo started a job to run these queries but it failed with the following error
> PERMISSION_DENIED: User does not have CREATE SCHEMA on Catalog 'main'.
> 
> For more details, open the job run page: https://adb-7642941683767724.4.azuredatabricks.net/?o=7642941683767724#job/1063000615105063/run/11318468
> You can skip the dashboard installation with skip_dashboards = True:
> dbdemos.install('uc-04-system-tables', skip_dashboards = True)

And yes, skipping the dashboards worked. Thank you!
