### ISSUE TITLE
I had to run the installation manually. How do I manually run dasboard installation after notesbook runs?

### ISSUE THREAD

**Issue by chmpsymp** [databricks-demos/dbdemos#52]
Hi, 

I was unable to run the dbdemo installation "dbdemos.install('uc-04-system-tables')", so I created tables and ran notebooks manually. Now I want to create the dasboards, though I can't seem to find any code that I can run for this. 
Can you direct me to code I can run to generate dasboards? 

Thanks!

**Comment by chmpsymp** [comment]
The error happens in the generation of system tables "RequestId=a861b9f4-ac6c-46a2-b07a-4e721ab098f8 ErrorClass=INVALID_STATE.UC_CLOUD_STORAGE_ACCESS_FAILURE] Failed to access cloud storage: AbfsRestOperationException exceptionTraceId=e68b0bb3-f1db-40f4-85d9-7785905642f6"

But I managed to create the table manually.

**Comment by QuentinAmbard** [comment]
did you try to install it in an existing catalog/Schema with the new option
?
Quentin Ambard

**Comment by chmpsymp** [comment]
When I try to run the installation, the script with the sql code never finishes: 

"--param query - the import needs the  query to be run first even empty.
CREATE SCHEMA IF NOT EXISTS `main`.`billing_forecast`;
CREATE TABLE IF NOT EXISTS `main`.`billing_forecast`.billing_forecast (sku STRING, workspace_id STRING);
INSERT INTO `main`.`billing_forecast`.billing_forecast (sku, workspace_id) SELECT 'ALL', 'ALL'
  WHERE NOT EXISTS (SELECT * FROM  `main`.`billing_forecast`.billing_forecast);


select distinct(workspace_id) from `main`.`billing_forecast`.billing_forecast order by workspace_id DESC LIMIT 1000;"

Is it possible that I can run the dashboard generation manually?

**Comment by QuentinAmbard** [comment]
is it because the endpoint can't start? There is no reason the query runs forever. What if you run the query manually what happens?

**Comment by chmpsymp** [comment]
Apparently there has been troubles with databricks sql yesterday and today. Now I managed to run the installation script after generating schemas manually. Thank you for your help :)

**Comment by chmpsymp** [comment]
Closed
