### ISSUE TITLE
customer-360 demo: error resulting in hidden system catalog [__databricks_internal]

### ISSUE THREAD

**Issue by dkah39** [databricks-demos/dbdemos#56]
I attempted to install the c360 customer_360 demo on an Azure premium workspace w/ unity enabled. However, my Azure Quota for the clusters the demo wanted to create was insufficient to perform the demo install. It errored out w/ an azure-quota-error. 

However, immediately after the error a system catalog appeared in Unity, [__databricks_internal], owned by `system`. 

(correlated, perhaps not causal)

It contains a schema for a DLT project I created quite a long time ago & tables with the prefix [__dlt_materialization_schema_{guid}].

<img width="532" alt="Screenshot 2023-08-03 at 9 35 46 AM" src="https://github.com/databricks-demos/dbdemos/assets/39970626/c4192413-7b7d-4cde-83ed-9c292a4b66f3">

I can't re-hide this table. Thoughts?

**Comment by QuentinAmbard** [comment]
Hi,
Non-metastore-admin users will not see it as long as permissions have not been explicitly granted. 
These catalogs/schemas are used to store internal tables for DLT, and will appear if DLT pipelines publishing to UC have been created in the workspace.
if you drop the DLT pipeline I'd assume the schema should disappear by itself no?

**Comment by QuentinAmbard** [comment]
for your install you can run it with use_current_cluster = True, it'll prevent from creating a new cluster and avoid the quota issue

**Comment by QuentinAmbard** [comment]
I think it's just because it created a new DLT pipeline and the new one are using the internal catalog. If you create one your self it'll appear too.

**Comment by dkah39** [comment]
Thanks. Reminder on how those hidden tables tie to DLT.
