### ISSUE TITLE
Data file creation issue writing to dbfs for demo: "Unit Testing Delta Live Table (DLT) for production-grade pipelines"

### ISSUE THREAD

**Issue by Alexandermafi** [databricks-demos/dbdemos#6]
"FileNotFoundError: [Errno 2] No such file or directory: '/dbfs/demos/retail/customers/test/spend_csv/spend.csv'"

![image](https://user-images.githubusercontent.com/3898762/211011100-838526bb-2e3f-4dad-b6f7-cac3973302a5.png)

Solution that worked for me was to use the following instead of "with open" to write files to dbfs
- dbutils.fs.put('/demos/retail/customers/test/spend_csv/spend.csv', spend_csv)
- dbutils.fs.put('/demos/retail/customers/test/users_json/users.json', users_json)

**Comment by QuentinAmbard** [comment]
thanks, 'w+' mode should do the trick also, I'll push a fix

**Comment by QuentinAmbard** [comment]
Should be fixed with:
`dbutils.fs.put('/demos/retail/customers/test/spend_csv/spend.csv', spend_csv, True)`
I'll be shipped in the next release - meanwhile it can be tested using the one in the repo: release/dbdemos-0.1.2-py3-none-any.whl

Thanks again!

**Comment by Alexandermafi** [comment]
Great to hear. Happy to help out and thanks for the awesome demos!
