### ISSUE TITLE
lakehouse-retail-c360

### ISSUE THREAD

**Issue by BrkSyd** [databricks-demos/dbdemos#62]
During the demo if you try to select any variables from the dropdown list in the html profile generated it returns a Javascript error. "Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase') " .

This can be fixed by adding the parameter minimal = True to ProfileReport function.

The 7th cell should be;

from pandas_profiling import ProfileReport
df_profile = ProfileReport(df, minimal = True,
                           correlations={
                               "auto": {"calculate": True},
                               "pearson": {"calculate": True},
                               "spearman": {"calculate": True},
                               "kendall": {"calculate": True},
                               "phi_k": {"calculate": True},
                               "cramers": {"calculate": True},
                           }, title="Profiling Report", progress_bar=False, infer_dtypes=False)
profile_html = df_profile.to_html()

displayHTML(profile_html)

**Comment by QuentinAmbard** [comment]
Hi @BrkSyd , We fully updated the retail c360 content, could you give it a try & let me know if it's still an issue? It's working when I tried

**Comment by BrkSyd** [comment]
Hey Quentin, issue seems to be resolved. I'll close it
