### ISSUE TITLE
Widget Parameters uc-04-system-tables

### ISSUE THREAD

**Issue by masonforce** [databricks-demos/dbdemos#63]
On the uc-04-system-tables demo, users can provide their own schema and catalog instead of default running on main. However, this option doesn't seem to show the proper parameter values in the widget for the dashboard (only shows ALL for Sku dropdown). Is this potentially an old dependency on the main catalog?

**Comment by QuentinAmbard** [comment]
what if you run the query ? I wonder if it's not a cache issue instead?

**Comment by masonforce** [comment]
That was it- I needed to run each query individually in the editor before the values would populate in the dashboard. Thanks

**Comment by QuentinAmbard** [comment]
ok cool, we'll check why it does this, it should refresh the underlying query
