### ISSUE TITLE
uc-01-acl Error when trying to ser row and column level access controls

### ISSUE THREAD

**Issue by PooyanGoodlabs** [databricks-demos/dbdemos#68]
For the "uc-01-acl" I'm facing the following error when trying to use ALTER TABLE SET ROW FILTER or ALTER TABLE ALTER COLUMN SET MASK 

ErrorClass=NOT_IMPLEMENTED.NOT_IMPLEMENTED] The UpdateTable row and column access policy operation is not currently implemented.

I have set up the demo on an interactive cluster(DBR 13.3 LTS) which is connected to UC, Catalog and schema and tables are successfully created but it seems the Row/Column level access controls are not enabled for the workspace. I'm using a pre-existing workspace/cluster.

**Comment by QuentinAmbard** [comment]
Hi @PooyanGoodlabs , I believe this is still a preview feature - pretty sure it'll go in public preview shortly :/

**Comment by charlesb** [comment]
Hi @QuentinAmbard, is there any Databricks Spark parameter we could use to enable this feature by any chance? :) (e.g. spark.databricks.rls.preview.enabled true)

**Comment by QuentinAmbard** [comment]
ah I wish I could share something simple like this ! Best thing to do is to ping your account team to be added to the preview. 
 think it's almost ready now, they delayed it a bit to improve the API I believe but it should be available soon

**Comment by QuentinAmbard** [comment]
Hey @charlesb , this is now public preview, closing this :)
