### ISSUE TITLE
'uc-04-system-tables'  setup job "dbdemos_billing_forecast_init_<username>" run fails the first time

### ISSUE THREAD

**Issue by saurabhshukla-db** [databricks-demos/dbdemos#71]
'uc-04-system-tables'  setup job "dbdemos_billing_forecast_init_<username>" run fails the first time with "unable to access the notebook ~/02-forecast-billing-tables"
when i run it second time , it just works fine.

**Comment by QuentinAmbard** [comment]
Hey, I think I fixed it, it was a small race condition in the toolkit. Let me know if this happens again!
