### ISSUE TITLE
dbdemos_lakehouse_fsi_credit_init_xxxx fails PERMISSION_DENIED: User does not have USE CATALOG on Catalog '__databricks_internal'.

### ISSUE THREAD

**Issue by snowch** [databricks-demos/dbdemos#74]
The job dbdemos_lakehouse_fsi_credit_init_xxxx is failing for me running this SQL:

```
[/Users/xxxx@databricks.com/lakehouse-fsi-credit/01-Data-Ingestion/01-DLT-Internal-Banking-Data-SQL](https://adb-xxxx.xx.azuredatabricks.net/?o=xxxx#workspace/Users%2Fchris.snow%40databricks.com%2Flakehouse-fsi-credit%2F01-Data-Ingestion%2F01-DLT-Internal-Banking-Data-SQL)
```

The error is:

```
PERMISSION_DENIED: User does not have USE CATALOG on Catalog '__databricks_internal'.
```

**Comment by QuentinAmbard** [comment]
Hi Chris, 
I believe it's a DLT bug, users shouldn't know about this catalog. Can you check if you have the permissions ? Maybe someone altered it but I don't think it's possible as it's internal only.

**Comment by QuentinAmbard** [comment]
looks like it's been fixed in ES-866429 - fixed will be released next from what I understood ?
