### ISSUE TITLE
lakehouse-fsi-fraud fails to install due to missing instance pool

### ISSUE THREAD

**Issue by sscrawfo** [databricks-demos/dbdemos#76]
Trying to install fraud demo in an Azure env.  Looks like if fails creating a job (workflow) due to referencing a specific instance pool that doesn't exist.

Error Response:
{"error_code": "INVALID_PARAMETER_VALUE", "message": "Cluster validation error: Can't find an instance pool with id: 0727-104344-hauls13-pool-uftxk0r6."}

Workflow:
{"name": "dbdemos_lakehouse_fsi_fraud_init_steven_crawford", "email_notifications": {"no_alert_for_skipped_runs": false}, "timeout_seconds": 0, "max_concurrent_runs": 1, "tasks": [{"task_key": "init_data", "notebook_task": {"notebook_path": "/Users/steven.crawford@databricks.com/AAA Fraud Demo/lakehouse-fsi-fraud/_resources/01-load-data", "source": "WORKSPACE"}, "job_cluster_key": "Shared_job_cluster", "timeout_seconds": 0, "email_notifications": {}}, {"task_key": "start_dlt_pipeline", "pipeline_task": {"pipeline_id": "b755026f-9f0f-4742-85cd-145751e7ff28", "full_refresh": false}, "timeout_seconds": 0, "email_notifications": {}, "depends_on": [{"task_key": "init_data"}]}, {"task_key": "clone_streaming_view", "depends_on": [{"task_key": "start_dlt_pipeline"}], "notebook_task": {"notebook_path": "/Users/steven.crawford@databricks.com/AAA Fraud Demo/lakehouse-fsi-fraud/_resources/02-DLT-Persist-Streaming-Views", "source": "WORKSPACE"}, "run_if": "ALL_SUCCESS", "new_cluster": {"num_workers": 1, "cluster_name": "", "spark_version": "12.2.x-scala2.12", "spark_conf": {"spark.databricks.dataLineage.enabled": "true"}, "spark_env_vars": {"PYSPARK_PYTHON": "/databricks/python3/bin/python3"}, "cluster_source": "JOB", "init_scripts": [], "data_security_mode": "USER_ISOLATION", "runtime_engine": "STANDARD", "custom_tags": {"project": "dbdemos", "demo": "lakehouse-fsi-fraud"}, "node_type_id": "Standard_D8ds_v4", "azure_attributes": {"first_on_demand": 1, "availability": "ON_DEMAND_AZURE", "spot_bid_max_price": -1}}, "timeout_seconds": 0, "email_notifications": {}}, {"task_key": "create_feature_and_automl_run", "notebook_task": {"notebook_path": "/Users/steven.crawford@databricks.com/AAA Fraud Demo/lakehouse-fsi-fraud/04-Data-Science-ML/04.1-AutoML-FSI-fraud", "source": "WORKSPACE"}, "job_cluster_key": "Shared_job_cluster", "timeout_seconds": 0, "email_notifications": {}, "depends_on": [{"task_key": "clone_streaming_view"}]}, {"task_key": "register_model", "notebook_task": {"notebook_path": "/Users/steven.crawford@databricks.com/AAA Fraud Demo/lakehouse-fsi-fraud/04-Data-Science-ML/04.2-automl-generated-notebook-fraud", "source": "WORKSPACE"}, "base_parameters": {"shap_enabled": "false"}, "job_cluster_key": "Shared_job_cluster", "timeout_seconds": 0, "email_notifications": {}, "depends_on": [{"task_key": "create_feature_and_automl_run"}]}, {"task_key": "create_model_serving_endpoint", "notebook_task": {"notebook_path": "/Users/steven.crawford@databricks.com/AAA Fraud Demo/lakehouse-fsi-fraud/04-Data-Science-ML/04.3-Model-serving-realtime-inference-fraud", "source": "WORKSPACE"}, "base_parameters": {"shap_enabled": "false"}, "job_cluster_key": "Shared_job_cluster", "timeout_seconds": 0, "email_notifications": {}, "depends_on": [{"task_key": "register_model"}]}], "job_clusters": [{"job_cluster_key": "Shared_job_cluster", "new_cluster": {"spark_version": "12.2.x-cpu-ml-scala2.12", "spark_conf": {"spark.master": "local[*, 4]", "spark.databricks.cluster.profile": "singleNode", "spark.databricks.dataLineage.enabled": "true"}, "custom_tags": {"ResourceClass": "SingleNode", "project": "dbdemos", "demo": "lakehouse-fsi-fraud"}, "spark_env_vars": {"PYSPARK_PYTHON": "/databricks/python3/bin/python3"}, "data_security_mode": "SINGLE_USER", "runtime_engine": "STANDARD", "num_workers": 0, "azure_attributes": {"first_on_demand": 1, "availability": "ON_DEMAND_AZURE", "spot_bid_max_price": -1}, "instance_pool_id": "0727-104344-hauls13-pool-uftxk0r6"}}], "format": "MULTI_TASK"}

**Comment by QuentinAmbard** [comment]
Thanks, just fixed it, will be released in a bit
