### ISSUE TITLE
DLT fails in the lakehouse-retail-c360

### ISSUE THREAD

**Issue by radeksdbx** [databricks-demos/dbdemos#77]
DLT fails with errors as in image
![image](https://github.com/databricks-demos/dbdemos/assets/147754871/e02a0bd4-86b0-4ac9-b000-02de1c354d33)
![Uploading image (1).png…]()

**Comment by QuentinAmbard** [comment]
Hey, I believe this was fixed in the latest release. Could you give it a try & let us know?
Thanks

**Comment by radeksdbx** [comment]
Hi Quentin, yes it's fixed. thanks
