### ISSUE TITLE
Query error in Lakehouse 360 Demo

### ISSUE THREAD

**Issue by koernigo** [databricks-demos/dbdemos#78]
![image](https://github.com/databricks-demos/dbdemos/assets/31516395/e5261cf7-6dfe-46b0-ac0a-b53f0291a4db)
Dashboard for Retail 360 demo.
The date column needs to be changed to"creation date " in the underlying query

**Comment by QuentinAmbard** [comment]
hey, thanks we fixed it with the new release, let me know if it's not the casei
