### ISSUE TITLE
IoT Platform Demo unable to install on Azure workspace

### ISSUE THREAD

**Issue by rebeccadatabricks** [databricks-demos/dbdemos#80]
Unable to install the demo on an Azure workspace. It works fine on AWS. The schema is indeed not found in the hive_metastore as indicated in the error message. Thanks :) 
![image](https://github.com/databricks-demos/dbdemos/assets/134005560/69261247-76ee-4958-b789-207f42db6f10)

**Comment by QuentinAmbard** [comment]
hey, closing this as everything is now on AI/BI & UC!
