### ISSUE TITLE
Issues with Dashboard

### ISSUE THREAD

**Issue by koernigo** [databricks-demos/dbdemos#82]
On the Customer Churn - Universal , one of the queries doesn't render:
![image](https://github.com/databricks-demos/dbdemos/assets/31516395/5f31de8a-b664-4b94-a081-1ea63acf7920)

Issue seems to be that there is a null in the query results

**Comment by QuentinAmbard** [comment]
Hey, I believe this was fixed in the latest release, please give it a try & let us know!
