### ISSUE TITLE
dbdemos_billing_forecast job runs with default job parameters

### ISSUE THREAD

**Issue by fannijako** [databricks-demos/dbdemos#88]
Task level parameters are not overwritten in dbdemos_billing_forecast job.

Gives an error: 
`com.databricks.sql.managedcatalog.acl.UnauthorizedAccessException: PERMISSION_DENIED: User does not have CREATE SCHEMA on Catalog 'main'.` on Cmd 4.

It works correctly when the notebook is run manually or when the job/task parameters are set to the correct catalog and schema values.

**Comment by QuentinAmbard** [comment]
Thanks @fannijako , I'll take a look in a bit, I thought users would have create schema by default, let me see what we can do instead.

**Comment by QuentinAmbard** [comment]
alright I found the issue, sorry it took me some time. SHould be fixed in the next release
