### ISSUE TITLE
Deprecate the audit log demo 

### ISSUE THREAD

**Issue by pponnaDB** [databricks-demos/dbdemos#93]
We still have a demo for audit logs - uc-04-audit-log . 

https://www.databricks.com/resources/demos/tutorials/governance/audit-log-with-databricks?itm_data=demo_center

Please deprecate it.

**Comment by QuentinAmbard** [comment]
will be removed from the list in the next release

**Comment by QuentinAmbard** [comment]
(deprecated dolly too)
