### ISSUE TITLE
INVALID_PARAMETER_VALUE: Missing required embeddings parameter: 'input'

### ISSUE THREAD

**Issue by rileynjohnson** [databricks-demos/dbdemos#97]
Hoping someone can help me past this one - done quite a bit of troubleshooting to no avail.

input_data = {"input": "Embed this sentence!"}
response = deploy_client.predict(endpoint="riley-databricks-bge-large-en", inputs=input_data)

HTTPError: 400 Client Error: Bad Request for url: https://eastus-c3.azuredatabricks.net/serving-endpoints/riley-databricks-bge-large-en/invocations. Response text: {"error":"Received error from databricks-model-serving","external_model_message":{"error_code":"INVALID_PARAMETER_VALUE","message":"INVALID_PARAMETER_VALUE: Missing required embeddings parameter: 'input'"}}

**Comment by QuentinAmbard** [comment]
hey, this looks like an issue with what your model is expecting. 
Depending of how you deployed your model, the input format might not be the good one.
What I usually do to make it easier is take an example and save it in mlflow as the schema when I register the model (you can look at our example we always do that). Then you can open the UI and your custom BGE endpoint, and ask for an input example.
It'll show you what's expected.
You can also check the advanced demo if you want to see how to send a pandas dataframe directly as input type.
Hope this helps!
